config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers
    collection do
      get 'admin'
    end
  end
  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  scope :by_recent,      -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :questions, dependent: :destroy

 def self.average_score
   scores = self.pluck(:points)
   scores.reduce(:+) / scores.size
 end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET questions/1/answers
  def index
    @answers = @question.answers
  end

  # GET questions/1/answers/1
  def show
  end

  # GET questions/1/answers/new
  def new
    @answer = @question.answers.build
  end

  # GET questions/1/answers/1/edit
  def edit
  end

  # POST questions/1/answers
  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to(admin_questions_path, flash: {success: 'Answer was successfully created.'} )
    else
      render action: 'new'
    end
  end

  # PUT questions/1/answers/1
  def update
    if params[:answer].nil?
      redirect_to(questions_path, flash: {error: "Please choose the answer!"}) and return
    end
    answer_id = params[:answer][:answer_id]
    answer = Answer.where(id: answer_id).first

    unless answer.nil?
      question = Question.joins(:answers).where(answers: {id: answer_id}).first
      correct_answer = question.answers.where(answers: {correct: true}).first
      if correct_answer.nil?
        redirect_to(questions_path, flash: {error: "The correct Answer is not defined by its creator"}) and return
      end
      if answer.correct
        current_user.points += 4
        current_user.save
        redirect_to(questions_path, flash: {success: "<div class='text-center'>#{question.name} is <h4><b>#{answer.name.upcase}</b></h4> Correct answer!</div><h4>.</h4>"}) and return
      else
        current_user.points -= 1
        current_user.save
        redirect_to(questions_path, flash: {error: "<div class='text-center'><h4><b>#{answer.name.upcase}</b></h4> is not the correct answer. <br>#{question.name} is a <h4><b>#{correct_answer.name.capitalize}</b></h4></div>"}) and return
      end
    end
    if @answer.update_attributes(answer_params)
      redirect_to(admin_questions_path, flash: {success: 'Answer was successfully updated.'})
    else
      render action: 'edit'
    end
  end

  # DELETE questions/1/answers/1
  def destroy
    @answer.destroy

    redirect_to admin_questions_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = @question.answers.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def answer_params
      params.require(:answer).permit(:name, :correct)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @top_users = User.order("points DESC")
    @average_score = User.average_score
    @players_count = User.count
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    @question = @questions.sample
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def admin
    @questions = Question.by_recent
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    if current_user
      @question = current_user.questions.build(question_params)
    end

    respond_to do |format|
      if @question.save
        format.html { redirect_to admin_questions_path, flash: {success: 'Question was successfully created.'} }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to admin_questions_path, flash: {success: 'Question was successfully updated.'} }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, flash: {success: 'Question was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'info' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
      when 'notice' then "alert alert-info"
      when 'email' then "alert alert-warning"
      when 'password' then "alert alert-warning"
    end
  end
end

app/views/answers/_form.html.erb
<%= form_for([@answer.question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this @answer from being saved:</h2>
      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container col-6 mt-5">
    <div class="card text-center">
      <div class="card-header h2">
        <%= form_name %> Answer
      </div>
      <div class="card-body">
        <h4 class="card-title">
          <div class="field">
            <%= f.text_field :name %>
          </div>
        </h4>
      </div>
      <div class="field mt-3">
        <%= f.label "Correct: " %>
        <%= f.check_box :correct, {checked: @answer.correct}  %>
      </div>
      <div class="card-footer text-muted">
        <div class="actions">
          <%= f.submit nil, class: 'btn btn-success'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/answers/edit.html.erb
<%= render 'answers/form', {:@answer => @answer, form_name: "Edit"} %>

app/views/answers/new.html.erb
<div class="text-center h3 mt-5"><%= @question.name %></div>
<%= render 'form', form_name: "Add" %>

app/views/home/_average.html.erb
<div class="container col-5">
  <div class="row">
    <div class="text-center">
      <div class="numberCircle"><%= @average_score %></div>
      Average Score
    </div>
    <div class="col-4 text-center mr-4"></div>
    <div class="ml-4 mb-3 text-center">
      <div class="numberCircle" style="background:#c0cbff"><%= @players_count %></div>
      Players
    </div>
  </div>
</div>

app/views/home/_table.html.erb
<div class="container col-10 table-wrapper-scroll-y my-custom-scrollbar mt-3 mb-5">
  <table class="table table-dark mb-5">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">Score</th>
      </tr>
    </thead>
    <tbody>
      <% @top_users.each.with_index(1) do |user, index| %>
        <tr>
          <th scope="row"><%= index %></th>
          <td><%= user.email %></td>
          <td><%= user.points %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag ( "trivia1.jpg"), class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag ( "trivia2.jpg"), class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag ( "trivia3.jpg"), class: "d-block w-100" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container mt-4 mb-4 col-4 text-center">
  <%= link_to questions_path, class: "btn btn-success btn-lg btn-block", style: "text-decoration: none;color:white" do%>
    Play the Game
  <% end %>
</div>

<%=render partial: "average" %>
<%=render partial: "table" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trivia108</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render "/shared/nav" %>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value.html_safe %>
      </div>
    <% end %>
    <%= yield %>
    <%= render "/shared/footer" %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container col-6 mt-5">
    <div class="card text-center">
      <div class="card-header h2">
        New Question
      </div>
      <div class="card-body">
        <h4 class="card-title">
          <div class="field">
            <%= form.text_field :name %>
          </div>
        </h4>
      </div>
      <div class="card-footer text-muted">
        <div class="actions">
          <%= form.submit nil, class: 'btn btn-success'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/admin.html.erb
<p id="notice"><%= notice %></p>
<div class="container col-6 mt-5">
  <%= link_to new_question_path, class: "btn btn-success btn-block", style: "text-decoration: none" do %>
    New Question
  <% end %>
</div>

<% @questions.each do |question| %>
  <div class="container col-8">
    <div class="card text-left mt-5 mb-5">
      <div class="card-header">
        Created at <%= question.created_at.strftime("%B %d, %Y") %>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-9 text-left">
            <h4 class="card-title">
              <%= question.name %>
            </h4>
          </div>
          <div class="col-3 text-right">
            <%= link_to edit_question_path(question), class: "btn btn-primary", style: "text-decoration: none" do %>
              Edit
            <% end %>
            <%= link_to question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style: "text-decoration: none" do %>
              Delete
            <% end %>
          </div>
        </div>
      </div>      
      <% question.answers.each do |answer| %>
        <div class="card-footer text-muted">
          <div class="row">
            <div class="col-6 text-left">
              <%= answer.name %>
            </div>
            <div class="col-3 text-left">
              <% if answer.correct %>
                <span class="badge badge-pill badge-success">Correct</span>
              <% end %>
            </div>
            <div class="col-3 text-right">
              <%= link_to edit_question_answer_path(answer.question, answer), class: "btn btn-primary", style: "text-decoration: none" do %>
                Edit
              <% end %>
              <%= link_to [answer.question, answer], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style: "text-decoration: none" do %>
                Delete
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="card-footer text-muted">
      <%= link_to new_question_answer_path(question.id), class: "btn btn-success", style: "text-decoration: none" do %>
        Add Answer
      <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<!-- <% @questions.each do |question| %> -->
  <!-- <% question.answers.each do |answer| %>
    <% render 'answers/form', {:@answer => answer, form_name: "Edit"} %>
  <% end %> -->
<!-- <% end %> -->
<%= form_for([@answer.question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this @answer from being saved:</h2>
      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container col-8">
    <div class="card text-left mt-3 mb-3">
      <div class="card-header">
        Created by <%= @question.user.email %>
      </div>
      <div class="card-body">
        <h4 class="card-title"><%= @question.name %></h4>
        <p class="card-text"></p>
      </div>
      <% @question.answers.each do |answer| %>
        <div class="card-footer text-left text-muted">
          <%= f.radio_button :answer_id, answer.id, checked: false %> <%= answer.name %>
        </div>
      <% end %>

      <div class="card-footer text-muted">
        <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<div class="container text-center h4 mt-0">
  Your score is: <b><%= current_user.points %></b>
</div>

app/views/questions/new.html.erb
<%= render 'form', question: @question %>

app/views/shared/_footer.html.erb
<footer id="footer" class=" navbar fixed-bottom">
  <div class="container col-12">
      <div class="col text-right">
        © 2020 Trivia 108
      </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #563d7c">
  <%= link_to "Trivia 108", root_path, class: "navbar-brand font-weight-bold text-light", style: "text-decoration: none" %>
  <ul class="nav">
    <% if user_signed_in? %>
    <li class="nav-item mr-1">
        <button type="button" class="btn btn-outline-warning">
          <%= link_to "Admin", admin_questions_path, class: "text-white", style: "text-decoration: none" %>
        </button>
      </li>
      <li class="nav-item">
        <button type="button" class="btn btn-default navbar-btn">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "text-light", style: "text-decoration: none" %>
        </button>
      </li>
    <% else %>
      <li class="nav-item">
        <button type="button" class="btn btn-default navbar-btn">
          <%= link_to "Log In", new_user_session_path, method: :get, class: "text-light", style: "text-decoration: none" %>
        </button>
      </li>
    <% end %>
  </ul>
</nav>